name: website_scraper
description: A website frontend source code extractor
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dio: ^4.0.4
  html: ^0.15.0

dev_dependencies:
  pedantic: ^1.11.0


